apiVersion: v1
kind: ConfigMap
metadata:
  name: pikachu-website-config
data:
  index.html: |
    <html>
    <body style="background-color: #f4f4f4; text-align: center; font-family: Arial;">
    <h1>⚡️ Welcome to Pikachu's DevOps Lab! ⚡️</h1>
    <p>If you are reading this, the ConfigMap successfully injected this text into the Nginx container!</p>
    </body>
    </html>
