apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pikachu-blog-ingress
spec:
  rules:
  - host: pikachu.blog.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-blog-wordpress
            port:
              number: 80
